# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
os: linux
dist: xenial

r:
  - release
  - bioc-devel
  - bioc-release

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

install:
  - R -e "renv::restore()"
  - R -e "install.packages(c('devtools', 'covr'))"

script:
  - R -e "devtools::check()"
